baseURL = ""

languageCode = "en-au"
title = "CHANGEME"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false

[params.reveal_hugo]
controls = true
controls_tutorial = true
progress = true
history = true
slide_number = true
center = false